### ISSUE TITLE
unity build discussion

### ISSUE THREAD

**Issue by geoffviola** [green7ea/cpp-compilation#3]
This Readme is great.

> You could put a function's definition in every source file that needs it but that's a terrible idea since the definition has to be the same everywhere if you want anything to work

I thought this was a bit of an oversimplification. What about unity builds: https://en.wikipedia.org/wiki/Single_Compilation_Unit?

**Comment by green7ea** [comment]
Thank you for the comment. First of all, I misused the word definition in many places, in most of them it should be declaration. This was fixed in a pull request and now the above paragraph reads:

> You could put a function's declaration in every source file that needs it but that's a terrible idea since the declaration has to be the same everywhere if you want anything to work.

I'm scared that mentioning a unity build might overwhelm the reader with too much information. The target audience is a novice C++ programmer and I find it's already a lot to process (I didn't know what to leave out).

What do you think about adding it as extra information in a short sentence with a link much like the mention of pimpl?

**Comment by geoffviola** [comment]
With the change to declaration, the document makes sense.

I think there is a lot of information on unity builds, but I'm not sure how it would fit in this document. It's worth noting, because it follows the language and is different from what most people are used to. The topic doesn't contradict the current document. It is just a specific case. A good explanation on unity builds would require a deeper discussion on tooling and link time optimization. So it is seems out of scope.
